<?	include ("../../include/dbconn.php");
	include ("../../include/login_ch.php");
	include ("../../include/function.php");

//	error_reporting(E_ALL);
//	ini_set("display_errors", 1);

	$board_dbname	=	"tbl_bosu_cost_set";

	$h_idx	=	trim($_REQUEST[h_idx]);
	$reg_mem_yn	=	trim($_REQUEST[reg_mem_yn]);
	$non_mem_yn	=	trim($_REQUEST[non_mem_yn]);
	$gen_mem_yn	=	trim($_REQUEST[gen_mem_yn]);
	$web_mem_yn	=	trim($_REQUEST[web_mem_yn]);
	$job_id      = $_SESSION["admin_id"];
	$job_date = date("YmdHis");

//echo "-";
//echo $reg_mem_yn;
	$sql = "delete from tbl_bosu_cost_set where h_idx='{$h_idx}' ";
	$r1 = db_query($sql);

//		echo $i;
		// 기간구분=1(입주기간내) / 회원종류=1(정회원)
	if($reg_mem_yn=="y"){
		$KEY1 = array();
		$KEY1["h_idx"] = $_REQUEST["h_idx"];
		$KEY1["gigan_gubun"] = "1";
		$KEY1["member_gubun"] = "1";
		$KEY1["dachul_gubun"] = "y";
		$KEY1["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_1"]);
		$KEY1["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_1"]);
		$KEY1["proof_cost"] = f_de_comma($_REQUEST["proof_cost_1"]);
		$KEY1["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_1"]);
		$KEY1["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_1"]);
		$KEY1["job_date"] = $job_date;
		$KEY1["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '1' ";
		$updatewhere.= "   AND member_gubun = '1' ";
		$updatewhere.= "   AND dachul_gubun = 'y' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
		//	print_r($KEY1);
		//	print_r($updatewhere);
		//	echo $KEY["doc_receive_date"];
		db_replace($KEY1,$board_dbname,$updatewhere,"h_idx");

		$KEY2 = array();
		$KEY2["h_idx"] = $_REQUEST["h_idx"];
		$KEY2["gigan_gubun"] = "1";
		$KEY2["member_gubun"] = "1";
		$KEY2["dachul_gubun"] = "n";
		$KEY2["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_2"]);
		$KEY2["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_2"]);
		$KEY2["proof_cost"] = f_de_comma($_REQUEST["proof_cost_2"]);
		$KEY2["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_2"]);
		$KEY2["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_2"]);
		$KEY2["job_date"] = $job_date;
		$KEY2["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '1' ";
		$updatewhere.= "   AND member_gubun = '1' ";
		$updatewhere.= "   AND dachul_gubun = 'n' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY2,$board_dbname,$updatewhere,"h_idx");
		
		$KEY9 = array();
		$KEY9["h_idx"] = $_REQUEST["h_idx"];
		$KEY9["gigan_gubun"] = "2";
		$KEY9["member_gubun"] = "1";
		$KEY9["dachul_gubun"] = "y";
		$KEY9["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_9"]);
		$KEY9["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_9"]);
		$KEY9["proof_cost"] = f_de_comma($_REQUEST["proof_cost_9"]);
		$KEY9["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_9"]);
		$KEY9["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_9"]);
		$KEY9["job_date"] = $job_date;
		$KEY9["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '2' ";
		$updatewhere.= "   AND member_gubun = '1' ";
		$updatewhere.= "   AND dachul_gubun = 'y' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY9,$board_dbname,$updatewhere,"h_idx");

		$KEY10 = array();
		$KEY10["h_idx"] = $_REQUEST["h_idx"];
		$KEY10["gigan_gubun"] = "2";
		$KEY10["member_gubun"] = "1";
		$KEY10["dachul_gubun"] = "n";
		$KEY10["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_10"]);
		$KEY10["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_10"]);
		$KEY10["proof_cost"] = f_de_comma($_REQUEST["proof_cost_10"]);
		$KEY10["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_10"]);
		$KEY10["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_10"]);
		$KEY10["job_date"] = $job_date;
		$KEY10["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '2' ";
		$updatewhere.= "   AND member_gubun = '1' ";
		$updatewhere.= "   AND dachul_gubun = 'n' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY10,$board_dbname,$updatewhere,"h_idx");

		$KEY17 = array();
		$KEY17["h_idx"] = $_REQUEST["h_idx"];
		$KEY17["gigan_gubun"] = "3";
		$KEY17["member_gubun"] = "1";
		$KEY17["dachul_gubun"] = "y";
		$KEY17["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_17"]);
		$KEY17["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_17"]);
		$KEY17["proof_cost"] = f_de_comma($_REQUEST["proof_cost_17"]);
		$KEY17["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_17"]);
		$KEY17["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_17"]);
		$KEY17["job_date"] = $job_date;
		$KEY17["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '3' ";
		$updatewhere.= "   AND member_gubun = '1' ";
		$updatewhere.= "   AND dachul_gubun = 'y' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY17,$board_dbname,$updatewhere,"h_idx");

		$KEY18 = array();
		$KEY18["h_idx"] = $_REQUEST["h_idx"];
		$KEY18["gigan_gubun"] = "3";
		$KEY18["member_gubun"] = "1";
		$KEY18["dachul_gubun"] = "n";
		$KEY18["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_18"]);
		$KEY18["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_18"]);
		$KEY18["proof_cost"] = f_de_comma($_REQUEST["proof_cost_18"]);
		$KEY18["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_18"]);
		$KEY18["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_18"]);
		$KEY18["job_date"] = $job_date;
		$KEY18["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '3' ";
		$updatewhere.= "   AND member_gubun = '1' ";
		$updatewhere.= "   AND dachul_gubun = 'n' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY18,$board_dbname,$updatewhere,"h_idx");

	}
	

//(비)회원 활성화 처리
	if($non_mem_yn=="y"){
		$KEY3 = array();
		$KEY3["h_idx"] = $_REQUEST["h_idx"];
		$KEY3["gigan_gubun"] = "1";
		$KEY3["member_gubun"] = "2";
		$KEY3["dachul_gubun"] = "y";
		$KEY3["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_3"]);
		$KEY3["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_3"]);
		$KEY3["proof_cost"] = f_de_comma($_REQUEST["proof_cost_3"]);
		$KEY3["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_3"]);
		$KEY3["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_3"]);
		$KEY3["job_date"] = $job_date;
		$KEY3["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '1' ";
		$updatewhere.= "   AND member_gubun = '2' ";
		$updatewhere.= "   AND dachul_gubun = 'y' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY3,$board_dbname,$updatewhere,"h_idx");

		$KEY4 = array();
		$KEY4["h_idx"] = $_REQUEST["h_idx"];
		$KEY4["gigan_gubun"] = "1";
		$KEY4["member_gubun"] = "2";
		$KEY4["dachul_gubun"] = "n";
		$KEY4["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_4"]);
		$KEY4["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_4"]);
		$KEY4["proof_cost"] = f_de_comma($_REQUEST["proof_cost_4"]);
		$KEY4["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_4"]);
		$KEY4["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_4"]);
		$KEY4["job_date"] = $job_date;
		$KEY4["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '1' ";
		$updatewhere.= "   AND member_gubun = '2' ";
		$updatewhere.= "   AND dachul_gubun = 'n' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY4,$board_dbname,$updatewhere,"h_idx");
		
	
		$KEY11 = array();
		$KEY11["h_idx"] = $_REQUEST["h_idx"];
		$KEY11["gigan_gubun"] = "2";
		$KEY11["member_gubun"] = "2";
		$KEY11["dachul_gubun"] = "y";
		$KEY11["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_11"]);
		$KEY11["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_11"]);
		$KEY11["proof_cost"] = f_de_comma($_REQUEST["proof_cost_11"]);
		$KEY11["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_11"]);
		$KEY11["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_11"]);
		$KEY11["job_date"] = $job_date;
		$KEY11["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '2' ";
		$updatewhere.= "   AND member_gubun = '2' ";
		$updatewhere.= "   AND dachul_gubun = 'y' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY11,$board_dbname,$updatewhere,"h_idx");

		$KEY12 = array();
		$KEY12["h_idx"] = $_REQUEST["h_idx"];
		$KEY12["gigan_gubun"] = "2";
		$KEY12["member_gubun"] = "2";
		$KEY12["dachul_gubun"] = "n";
		$KEY12["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_12"]);
		$KEY12["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_12"]);
		$KEY12["proof_cost"] = f_de_comma($_REQUEST["proof_cost_12"]);
		$KEY12["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_12"]);
		$KEY12["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_12"]);
		$KEY12["job_date"] = $job_date;
		$KEY12["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '2' ";
		$updatewhere.= "   AND member_gubun = '2' ";
		$updatewhere.= "   AND dachul_gubun = 'n' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY12,$board_dbname,$updatewhere,"h_idx");

		$KEY19 = array();
		$KEY19["h_idx"] = $_REQUEST["h_idx"];
		$KEY19["gigan_gubun"] = "3";
		$KEY19["member_gubun"] = "2";
		$KEY19["dachul_gubun"] = "y";
		$KEY19["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_19"]);
		$KEY19["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_19"]);
		$KEY19["proof_cost"] = f_de_comma($_REQUEST["proof_cost_19"]);
		$KEY19["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_19"]);
		$KEY19["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_19"]);
		$KEY19["job_date"] = $job_date;
		$KEY19["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '3' ";
		$updatewhere.= "   AND member_gubun = '2' ";
		$updatewhere.= "   AND dachul_gubun = 'y' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY19,$board_dbname,$updatewhere,"h_idx");

		$KEY20 = array();
		$KEY20["h_idx"] = $_REQUEST["h_idx"];
		$KEY20["gigan_gubun"] = "3";
		$KEY20["member_gubun"] = "2";
		$KEY20["dachul_gubun"] = "n";
		$KEY20["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_20"]);
		$KEY20["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_20"]);
		$KEY20["proof_cost"] = f_de_comma($_REQUEST["proof_cost_20"]);
		$KEY20["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_20"]);
		$KEY20["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_20"]);
		$KEY20["job_date"] = $job_date;
		$KEY20["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '3' ";
		$updatewhere.= "   AND member_gubun = '2' ";
		$updatewhere.= "   AND dachul_gubun = 'n' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY20,$board_dbname,$updatewhere,"h_idx");
	}

//일반회원 활성화 처리
	if($gen_mem_yn=="y"){

		$KEY5 = array();
		$KEY5["h_idx"] = $_REQUEST["h_idx"];
		$KEY5["gigan_gubun"] = "1";
		$KEY5["member_gubun"] = "3";
		$KEY5["dachul_gubun"] = "y";
		$KEY5["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_5"]);
		$KEY5["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_5"]);
		$KEY5["proof_cost"] = f_de_comma($_REQUEST["proof_cost_5"]);
		$KEY5["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_5"]);
		$KEY5["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_5"]);
		$KEY5["job_date"] = $job_date;
		$KEY5["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '1' ";
		$updatewhere.= "   AND member_gubun = '3' ";
		$updatewhere.= "   AND dachul_gubun = 'y' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY5,$board_dbname,$updatewhere,"h_idx");

		$KEY6 = array();
		$KEY6["h_idx"] = $_REQUEST["h_idx"];
		$KEY6["gigan_gubun"] = "1";
		$KEY6["member_gubun"] = "3";
		$KEY6["dachul_gubun"] = "n";
		$KEY6["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_6"]);
		$KEY6["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_6"]);
		$KEY6["proof_cost"] = f_de_comma($_REQUEST["proof_cost_6"]);
		$KEY6["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_6"]);
		$KEY6["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_6"]);
		$KEY6["job_date"] = $job_date;
		$KEY6["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '1' ";
		$updatewhere.= "   AND member_gubun = '3' ";
		$updatewhere.= "   AND dachul_gubun = 'n' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY6,$board_dbname,$updatewhere,"h_idx");

		$KEY13 = array();
		$KEY13["h_idx"] = $_REQUEST["h_idx"];
		$KEY13["gigan_gubun"] = "2";
		$KEY13["member_gubun"] = "3";
		$KEY13["dachul_gubun"] = "y";
		$KEY13["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_13"]);
		$KEY13["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_13"]);
		$KEY13["proof_cost"] = f_de_comma($_REQUEST["proof_cost_13"]);
		$KEY13["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_13"]);
		$KEY13["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_13"]);
		$KEY13["job_date"] = $job_date;
		$KEY13["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '2' ";
		$updatewhere.= "   AND member_gubun = '3' ";
		$updatewhere.= "   AND dachul_gubun = 'y' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY13,$board_dbname,$updatewhere,"h_idx");

		$KEY14 = array();
		$KEY14["h_idx"] = $_REQUEST["h_idx"];
		$KEY14["gigan_gubun"] = "2";
		$KEY14["member_gubun"] = "3";
		$KEY14["dachul_gubun"] = "n";
		$KEY14["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_14"]);
		$KEY14["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_14"]);
		$KEY14["proof_cost"] = f_de_comma($_REQUEST["proof_cost_14"]);
		$KEY14["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_14"]);
		$KEY14["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_14"]);
		$KEY14["job_date"] = $job_date;
		$KEY14["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '2' ";
		$updatewhere.= "   AND member_gubun = '3' ";
		$updatewhere.= "   AND dachul_gubun = 'n' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY14,$board_dbname,$updatewhere,"h_idx");
		

		$KEY21 = array();
		$KEY21["h_idx"] = $_REQUEST["h_idx"];
		$KEY21["gigan_gubun"] = "3";
		$KEY21["member_gubun"] = "3";
		$KEY21["dachul_gubun"] = "y";
		$KEY21["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_21"]);
		$KEY21["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_21"]);
		$KEY21["proof_cost"] = f_de_comma($_REQUEST["proof_cost_21"]);
		$KEY21["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_21"]);
		$KEY21["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_21"]);
		$KEY21["job_date"] = $job_date;
		$KEY21["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '3' ";
		$updatewhere.= "   AND member_gubun = '3' ";
		$updatewhere.= "   AND dachul_gubun = 'y' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY21,$board_dbname,$updatewhere,"h_idx");

		$KEY22 = array();
		$KEY22["h_idx"] = $_REQUEST["h_idx"];
		$KEY22["gigan_gubun"] = "3";
		$KEY22["member_gubun"] = "3";
		$KEY22["dachul_gubun"] = "n";
		$KEY22["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_22"]);
		$KEY22["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_22"]);
		$KEY22["proof_cost"] = f_de_comma($_REQUEST["proof_cost_22"]);
		$KEY22["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_22"]);
		$KEY22["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_22"]);
		$KEY22["job_date"] = $job_date;
		$KEY22["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '3' ";
		$updatewhere.= "   AND member_gubun = '3' ";
		$updatewhere.= "   AND dachul_gubun = 'n' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY22,$board_dbname,$updatewhere,"h_idx");
	}

//웹회원 활성화 처리
	if($web_mem_yn=="y"){

		$KEY7 = array();
		$KEY7["h_idx"] = $_REQUEST["h_idx"];
		$KEY7["gigan_gubun"] = "1";
		$KEY7["member_gubun"] = "4";
		$KEY7["dachul_gubun"] = "y";
		$KEY7["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_7"]);
		$KEY7["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_7"]);
		$KEY7["proof_cost"] = f_de_comma($_REQUEST["proof_cost_7"]);
		$KEY7["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_7"]);
		$KEY7["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_7"]);
		$KEY7["job_date"] = $job_date;
		$KEY7["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '1' ";
		$updatewhere.= "   AND member_gubun = '4' ";
		$updatewhere.= "   AND dachul_gubun = 'y' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY7,$board_dbname,$updatewhere,"h_idx");

		$KEY8 = array();
		$KEY8["h_idx"] = $_REQUEST["h_idx"];
		$KEY8["gigan_gubun"] = "1";
		$KEY8["member_gubun"] = "4";
		$KEY8["dachul_gubun"] = "n";
		$KEY8["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_8"]);
		$KEY8["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_8"]);
		$KEY8["proof_cost"] = f_de_comma($_REQUEST["proof_cost_8"]);
		$KEY8["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_8"]);
		$KEY8["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_8"]);
		$KEY8["job_date"] = $job_date;
		$KEY8["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '1' ";
		$updatewhere.= "   AND member_gubun = '4' ";
		$updatewhere.= "   AND dachul_gubun = 'n' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY8,$board_dbname,$updatewhere,"h_idx");

		$KEY15 = array();
		$KEY15["h_idx"] = $_REQUEST["h_idx"];
		$KEY15["gigan_gubun"] = "2";
		$KEY15["member_gubun"] = "4";
		$KEY15["dachul_gubun"] = "y";
		$KEY15["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_15"]);
		$KEY15["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_15"]);
		$KEY15["proof_cost"] = f_de_comma($_REQUEST["proof_cost_15"]);
		$KEY15["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_15"]);
		$KEY15["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_15"]);
		$KEY15["job_date"] = $job_date;
		$KEY15["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '2' ";
		$updatewhere.= "   AND member_gubun = '4' ";
		$updatewhere.= "   AND dachul_gubun = 'y' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY15,$board_dbname,$updatewhere,"h_idx");

		$KEY16 = array();
		$KEY16["h_idx"] = $_REQUEST["h_idx"];
		$KEY16["gigan_gubun"] = "2";
		$KEY16["member_gubun"] = "4";
		$KEY16["dachul_gubun"] = "n";
		$KEY16["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_16"]);
		$KEY16["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_16"]);
		$KEY16["proof_cost"] = f_de_comma($_REQUEST["proof_cost_16"]);
		$KEY16["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_16"]);
		$KEY16["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_16"]);
		$KEY16["job_date"] = $job_date;
		$KEY16["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '2' ";
		$updatewhere.= "   AND member_gubun = '4' ";
		$updatewhere.= "   AND dachul_gubun = 'n' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY16,$board_dbname,$updatewhere,"h_idx");


		$KEY23 = array();
		$KEY23["h_idx"] = $_REQUEST["h_idx"];
		$KEY23["gigan_gubun"] = "3";
		$KEY23["member_gubun"] = "4";
		$KEY23["dachul_gubun"] = "y";
		$KEY23["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_23"]);
		$KEY23["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_23"]);
		$KEY23["proof_cost"] = f_de_comma($_REQUEST["proof_cost_23"]);
		$KEY23["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_23"]);
		$KEY23["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_23"]);
		$KEY23["job_date"] = $job_date;
		$KEY23["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '3' ";
		$updatewhere.= "   AND member_gubun = '4' ";
		$updatewhere.= "   AND dachul_gubun = 'y' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY23,$board_dbname,$updatewhere,"h_idx");

		$KEY24 = array();
		$KEY24["h_idx"] = $_REQUEST["h_idx"];
		$KEY24["gigan_gubun"] = "3";
		$KEY24["member_gubun"] = "4";
		$KEY24["dachul_gubun"] = "n";
		$KEY24["ijeon_bosu_cost"] = f_de_comma($_REQUEST["ijeon_bosu_cost_24"]);
		$KEY24["ijeon_bosu_vat"] = f_de_comma($_REQUEST["ijeon_bosu_vat_24"]);
		$KEY24["proof_cost"] = f_de_comma($_REQUEST["proof_cost_24"]);
		$KEY24["sintak_bosu_cost"] = f_de_comma($_REQUEST["sintak_bosu_cost_24"]);
		$KEY24["sintak_bosu_vat"] = f_de_comma($_REQUEST["sintak_bosu_vat_24"]);
		$KEY24["job_date"] = $job_date;
		$KEY24["job_id"] = $job_id;
		$updatewhere = " WHERE h_idx = '".$_REQUEST["h_idx"]."' ";
		$updatewhere.= "   AND gigan_gubun = '3' ";
		$updatewhere.= "   AND member_gubun = '4' ";
		$updatewhere.= "   AND dachul_gubun = 'n' ";
//			$updatewhere = " WHERE a1 = '".$_REQUEST["a1_".$i]."'  ";
//			print_r($KEY1);
//			print_r($updatewhere);
//			echo $KEY["doc_receive_date"];
		db_replace($KEY24,$board_dbname,$updatewhere,"h_idx");
	}


	echo "<meta http-equiv='Content-Type' content='text/html; charset=utf-8'>";
	echo "<html>";
	echo "<body>";
	echo "<center>";
	echo "<br>";
	echo "<input type=button value=' 저장 완료! ' onclick='javascript:opener.document.ffm.submit();window.close();'>";
	echo "</center>";
	echo "</body>";
	echo "</html>";
	exit;
?>